workflows:  
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "Gametopia/Gametopia.xcodeproj" # Isikan nama project Anda.
          XCODE_WORKSPACE : "Gametopia/Gametopia.xcworkspace" # Isikan nama workspace Anda.
          XCODE_SCHEME: "Gametopia" # Isikan nama scheme project Anda.
    scripts:
      - name: iOS test
        script: | 
          xcode-project run-tests \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --device "iPhone 12"
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO          
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - patriciafiona3@gmail.com # Isikan email untuk notifikasi status building.